# Docker Compose for CorpGrid development environment
version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: corpgrid
      POSTGRES_USER: corpgrid
      POSTGRES_PASSWORD: corpgrid
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U corpgrid"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: corpgrid
      MINIO_ROOT_PASSWORD: corpgrid123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Create bucket on startup
  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 corpgrid corpgrid123;
      mc mb --ignore-existing myminio/corpgrid-bundles;
      mc mb --ignore-existing myminio/corpgrid-results;
      mc mb --ignore-existing myminio/corpgrid-checkpoints;
      "

volumes:
  postgres_data:
  minio_data:
